package entity;
// Generated 2020-02-08 14:45:48 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Dane generated by hbm2java
 */
public class Dane  implements java.io.Serializable {


     private Integer id;
     private String nazwa;
     private int idWlasciciela;
     private byte[] dana;
     private Date dataDodania;
     private Integer idKatalogu;
     private String widocznosc;

    public Dane() {
    }

	
    public Dane(String nazwa, int idWlasciciela, Date dataDodania) {
        this.nazwa = nazwa;
        this.idWlasciciela = idWlasciciela;
        this.dataDodania = dataDodania;
    }
    public Dane(String nazwa, int idWlasciciela, byte[] dana, Date dataDodania, Integer idKatalogu, String widocznosc) {
       this.nazwa = nazwa;
       this.idWlasciciela = idWlasciciela;
       this.dana = dana;
       this.dataDodania = dataDodania;
       this.idKatalogu = idKatalogu;
       this.widocznosc = widocznosc;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNazwa() {
        return this.nazwa;
    }
    
    public void setNazwa(String nazwa) {
        this.nazwa = nazwa;
    }
    public int getIdWlasciciela() {
        return this.idWlasciciela;
    }
    
    public void setIdWlasciciela(int idWlasciciela) {
        this.idWlasciciela = idWlasciciela;
    }
    public byte[] getDana() {
        return this.dana;
    }
    
    public void setDana(byte[] dana) {
        this.dana = dana;
    }
    public Date getDataDodania() {
        return this.dataDodania;
    }
    
    public void setDataDodania(Date dataDodania) {
        this.dataDodania = dataDodania;
    }
    public Integer getIdKatalogu() {
        return this.idKatalogu;
    }
    
    public void setIdKatalogu(Integer idKatalogu) {
        this.idKatalogu = idKatalogu;
    }
    public String getWidocznosc() {
        return this.widocznosc;
    }
    
    public void setWidocznosc(String widocznosc) {
        this.widocznosc = widocznosc;
    }




}


