package entity;
// Generated 2020-02-08 14:45:48 by Hibernate Tools 4.3.1



/**
 * Katalog generated by hbm2java
 */
public class Katalog  implements java.io.Serializable {


     private Integer id;
     private String nazwa;
     private Double pojemnosc;
     private String nadkatalog;
     private String podkatalog;

    public Katalog() {
    }

	
    public Katalog(String nazwa) {
        this.nazwa = nazwa;
    }
    public Katalog(String nazwa, Double pojemnosc, String nadkatalog, String podkatalog) {
       this.nazwa = nazwa;
       this.pojemnosc = pojemnosc;
       this.nadkatalog = nadkatalog;
       this.podkatalog = podkatalog;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNazwa() {
        return this.nazwa;
    }
    
    public void setNazwa(String nazwa) {
        this.nazwa = nazwa;
    }
    public Double getPojemnosc() {
        return this.pojemnosc;
    }
    
    public void setPojemnosc(Double pojemnosc) {
        this.pojemnosc = pojemnosc;
    }
    public String getNadkatalog() {
        return this.nadkatalog;
    }
    
    public void setNadkatalog(String nadkatalog) {
        this.nadkatalog = nadkatalog;
    }
    public String getPodkatalog() {
        return this.podkatalog;
    }
    
    public void setPodkatalog(String podkatalog) {
        this.podkatalog = podkatalog;
    }




}


