package entity;
// Generated 2020-02-08 14:44:18 by Hibernate Tools 4.3.1



/**
 * Uzytkownik generated by hbm2java
 */
public class Uzytkownik  implements java.io.Serializable {


     private Integer id;
     private String login;
     private String haslo;
     private boolean czyadmin;

    public Uzytkownik() {
    }

	
    public Uzytkownik(String login, boolean czyadmin) {
        this.login = login;
        this.czyadmin = czyadmin;
    }
    public Uzytkownik(String login, String haslo, boolean czyadmin) {
       this.login = login;
       this.haslo = haslo;
       this.czyadmin = czyadmin;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }
    public String getHaslo() {
        return this.haslo;
    }
    
    public void setHaslo(String haslo) {
        this.haslo = haslo;
    }
    public boolean isCzyadmin() {
        return this.czyadmin;
    }
    
    public void setCzyadmin(boolean czyadmin) {
        this.czyadmin = czyadmin;
    }




}


